### ISSUE TITLE
npm package still has console logs

### ISSUE THREAD

**Issue by mrphelz** [pvencill/slugin#2]
You removed console logs from the source but those are still present when installing your plugin with npm

**Comment by pvencill** [comment]
The only ones left are what's in the dependent modules.

**Comment by pdesterlich** [comment]
i think i sorted this out: when i installed through npm (on february 10) i got version 0.0.11; now i see you bumped version to 0.0.12 and if i change my package.json to that version i get current files (without console.log).
So maybe it was just npm which needed your version bump in order to get and deploy latest version.
